"""add estimated duration to routes

Revision ID: 6616ebed6722
Revises: 7a0b2f41195a
Create Date: 2026-02-24 10:19:33.003938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6616ebed6722'
down_revision: Union[str, Sequence[str], None] = '7a0b2f41195a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    # Step 1: Add column as nullable
    op.add_column(
        'routes',
        sa.Column('estimated_duration_minutes', sa.Integer(), nullable=True)
    )

    # Step 2: Fill existing rows
    op.execute(
        "UPDATE routes SET estimated_duration_minutes = 60"
    )

    # Step 3: Make column NOT NULL
    op.alter_column(
        'routes',
        'estimated_duration_minutes',
        nullable=False
    )
    
# def upgrade() -> None:
#     """Upgrade schema."""    
#     op.add_column('routes', sa.Column('estimated_duration_minutes', sa.Integer(), nullable=False))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('routes', 'estimated_duration_minutes')
    # ### end Alembic commands ###
