"""add is_reached to route_stops

Revision ID: 7e842cea94bb
Revises: 26092e0cace3
Create Date: 2026-02-26 11:20:21.822855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e842cea94bb'
down_revision: Union[str, Sequence[str], None] = '26092e0cace3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('route_stops', sa.Column('is_reached', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('route_stops', 'is_reached')
    # ### end Alembic commands ###
